
language: java
sudo: false

jdk:
- openjdk8
- openjdk10

before_install:
- make dependencies

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UmM3Ic71tkCGHQME3ih/mTwVZfHNW3hg5nZWfDyZuA73YuWHf76Fg6oYG1hkdSvFftuFPe1OrgqYkKFgz3PwziDIKKND1TqwG99atVC5YqCG9SJDSHxed2rTF73BSIcLrFfyFtRBFBXIhesTT6l1rw1Jmy71ysSRCknwPwBgt24=
  file: target/OSMembrane.jar
  on:
    repo: openstreetmap/OSMembrane
    tags: true
    all_branches: true
    jdk: openjdk10
