//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 03:13:47 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://osmembrane.de/model/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.osmembrane.model.xml;
