//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.27 at 08:53:01 PM MEZ 
//

package de.openstreetmap.josm.tagging_preset_1;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for check complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="check">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="text_context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="default" type="{http://josm.openstreetmap.de/tagging-preset-1.0}check_default" />
 *       &lt;attribute name="use_last_as_default" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="value_on" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value_off" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "check")
public class Check {

    @XmlAttribute(required = true)
    protected String key;
    @XmlAttribute
    protected String text;
    @XmlAttribute(name = "text_context")
    protected String textContext;
    @XmlAttribute(name = "default")
    protected CheckDefault _default;
    @XmlAttribute(name = "use_last_as_default")
    protected Boolean useLastAsDefault;
    @XmlAttribute
    protected Boolean required;
    @XmlAttribute(name = "value_on")
    protected String valueOn;
    @XmlAttribute(name = "value_off")
    protected String valueOff;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the key property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textContext property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTextContext() {
        return textContext;
    }

    /**
     * Sets the value of the textContext property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTextContext(String value) {
        this.textContext = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return possible object is {@link CheckDefault }
     * 
     */
    public CheckDefault getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *            allowed object is {@link CheckDefault }
     * 
     */
    public void setDefault(CheckDefault value) {
        this._default = value;
    }

    /**
     * Gets the value of the useLastAsDefault property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isUseLastAsDefault() {
        return useLastAsDefault;
    }

    /**
     * Sets the value of the useLastAsDefault property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setUseLastAsDefault(Boolean value) {
        this.useLastAsDefault = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the valueOn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValueOn() {
        return valueOn;
    }

    /**
     * Sets the value of the valueOn property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValueOn(String value) {
        this.valueOn = value;
    }

    /**
     * Gets the value of the valueOff property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValueOff() {
        return valueOff;
    }

    /**
     * Sets the value of the valueOff property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValueOff(String value) {
        this.valueOff = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed
     * property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and the value is the string
     * value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute by
     * updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
