//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.27 at 08:53:01 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://josm.openstreetmap.de/tagging-preset-1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.openstreetmap.josm.tagging_preset_1;

