//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.27 at 08:53:01 PM MEZ 
//

package de.openstreetmap.josm.tagging_preset_1;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for role complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="role">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="text_context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="requisite" type="{http://josm.openstreetmap.de/tagging-preset-1.0}role_requisite" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "role")
public class Role {

    @XmlAttribute
    protected String key;
    @XmlAttribute
    protected String text;
    @XmlAttribute(name = "text_context")
    protected String textContext;
    @XmlAttribute
    protected RoleRequisite requisite;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected BigInteger count;
    @XmlAttribute
    protected Boolean required;

    /**
     * Gets the value of the key property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textContext property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTextContext() {
        return textContext;
    }

    /**
     * Sets the value of the textContext property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTextContext(String value) {
        this.textContext = value;
    }

    /**
     * Gets the value of the requisite property.
     * 
     * @return possible object is {@link RoleRequisite }
     * 
     */
    public RoleRequisite getRequisite() {
        return requisite;
    }

    /**
     * Sets the value of the requisite property.
     * 
     * @param value
     *            allowed object is {@link RoleRequisite }
     * 
     */
    public void setRequisite(RoleRequisite value) {
        this.requisite = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

}
